//
//  ViewController.swift
//  iOSQuiz
//
//  Created by administrator on 30/11/2021.
//

import UIKit

class ViewController: UIViewController {

    var track: Int = 0
    let questiossArray: [String] =
    ["Xcode is designed so that we build the user interface first",
    "Why Auto Layout?",
    "What is an ambiguous layout?",
    "What is an Outlet?",
    "What is a Connection?",
    "What is an Action?"]
    
    let answersArray: [String] =
    ["True",
     "We don't want to create a separate layout for all of the different types of screen sizes our users will interact with our application",
    "When our view object has a blue and red border or\nWhen there\'s more than one possible layout given the constraints",
    "An Outlet connects a property in code to a View object in a storyboard",
    "Outlets and Actions create a connection from the storyboard to the View Controller code",
    "An Action connects an event generated by a user interacting with a storyboard object to a method in our code"]
    
    @IBOutlet weak var questionLabel: UILabel!
    @IBOutlet weak var answerLabel: UILabel!

    
    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view.
        track = 0
        updateLabels()
    }

    
    @IBAction func answerButton(_ sender: UIButton) {
        answerLabel.isHidden = !answerLabel.isHidden
    }
    
    @IBAction func nextButton(_ sender: UIButton) {
        updateLabels()
    }
    
    private func updateLabels() {
        questionLabel.text = questiossArray[track]
        answerLabel.text = answersArray[track]
        answerLabel.isHidden = true
        track += 1
        if(track >= questiossArray.count){
            track = 0
        }
    }

}

